[package]
name = "tetanus-common"
version = "0.1.0"
authors = ["Lachlan Barker <lachlan@chr0me.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
